### ISSUE TITLE
'Edit' Feature

### ISSUE THREAD

**Issue by JamesStallings** [benbrown/shuttlecraft#138]
It (the 'edit' feature, that is), seems to be present only on a most tenuous basis. I even just used it on a post I made moments ago, went to use it again on the same post, and the pencil icon had left the tool pane beneath the post.

**Comment by benbrown** [comment]
Woops! Yeah looks like I broke it.

**Comment by benbrown** [comment]
@JamesStallings this should be fixed if you pull the main branch
