### ISSUE TITLE
The .env file is acting weird in the repo

### ISSUE THREAD

**Issue by benbrown** [benbrown/shuttlecraft#32]
it overwrote my local .env file!

**Comment by benbrown** [comment]
@anildash is there some trick to including a .env file in a repo so glitch gets properly seeded, but .. not have it be a big PITA to exclude from commits?

**Comment by patrickmcurry** [comment]
I'd consider putting the .env filename in your .gitignore list, and trick npm install or the first time the app runs into creating the .env file (if it doesn't exist) with your default values in it.

**Comment by patrickmcurry** [comment]
Could also ship an `example.env` file in the repo isntead of `.env` -- and when the app runs, if `.env` doesn't exist, then it copies `example.env` to `.env` and tells the user to go edit `.env`. (just brainstorming)

**Comment by benbrown** [comment]
@patrickmcurry this should be fixed. you may have to fix it one last time after merging latest.
