### ISSUE TITLE
Reply to notification fails

### ISSUE THREAD

**Issue by ringtailsoftware** [benbrown/shuttlecraft#55]
Pressing reply button from the notifications view fails.
"TypeError post is null"

Possibly because the message posting form isn't present on that page.

**Comment by benbrown** [comment]
This should be fixed in latest main since the post form now lives on its own page…

**Comment by benbrown** [comment]
@ringtailsoftware does this still happen for you?

**Comment by ringtailsoftware** [comment]
Fixed

**Comment by benbrown** [comment]
Thanks for confirming.
