### ISSUE TITLE
Following user on pixelfed.de fails

### ISSUE THREAD

**Issue by ringtailsoftware** [benbrown/shuttlecraft#75]
Following tobyjaffey@pixelfed.de doesn't add the user to the followers list, but the new follower does appear on pixelfed.de.

I think that pixelfed.de may not be replying with an Accept

**Comment by benbrown** [comment]
Huh! It definitely does not log the follow until the accept comes back.

**Comment by benbrown** [comment]
Figured this out! Pixelfed uses a slightly different content type when sending to the inbox. Should work now.
