### ISSUE TITLE
Feature Suggestion: allow profile edit

### ISSUE THREAD

**Issue by PurpleStarChild** [benbrown/shuttlecraft#77]
Add an area that allows for setting profile page. This should at minimum include a self description area. 

Optimally it would also allow for listing links and link validation to indicate identity proof.

**Comment by ringtailsoftware** [comment]
Adds profile/header image upload and self description editing
https://github.com/benbrown/shuttlecraft/pull/62

**Comment by benbrown** [comment]
dupe of #29
